### ISSUE TITLE
Android Crash at launch

### ISSUE THREAD

**Issue by alamboley** [distriqt/ANE-Firebase#120]
Hi, trying to add this ANE to a project (removing Google Analytics for Firebase analytics).

When launching on Android device, it crashes at launch:
11-28 12:21:11.597: D/ViewRootImpl@65a6639[Snapstars](3735): dispatchDetachedFromWindow
11-28 12:21:11.598: W/WindowManager(3735): Failed looking up window
11-28 12:21:11.598: W/WindowManager(3735): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@8b9147e does not exist
11-28 12:21:11.598: W/WindowManager(3735): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10302)
11-28 12:21:11.598: W/WindowManager(3735): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:10293)
11-28 12:21:11.598: W/WindowManager(3735): 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2632)
11-28 12:21:11.598: W/WindowManager(3735): 	at com.android.server.wm.Session.remove(Session.java:208)
11-28 12:21:11.598: W/WindowManager(3735): 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3676)
11-28 12:21:11.598: W/WindowManager(3735): 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:6583)
11-28 12:21:11.598: W/WindowManager(3735): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4082)
11-28 12:21:11.598: W/WindowManager(3735): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-28 12:21:11.598: W/WindowManager(3735): 	at android.os.Looper.loop(Looper.java:154)
11-28 12:21:11.598: W/WindowManager(3735): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-28 12:21:11.598: W/WindowManager(3735): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
11-28 12:21:11.598: D/InputTransport(3735): Input channel destroyed: fd=414

Any ideas?
```xml
<manifestAdditions><![CDATA[<manifest android:installLocation="auto">
<uses-sdk android:minSdkVersion="9" android:targetSdkVersion="24" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
<uses-permission android:name="android.permission.GET_ACCOUNTS"/>
<uses-permission android:name="android.permission.GET_TASKS"/>
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_PHONE_STATE"/>
<uses-permission android:name="android.permission.VIBRATE"/>
<uses-permission android:name="android.permission.WAKE_LOCK"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>

<permission android:name="air.com.ccm.Snapstars.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
<uses-permission android:name="air.com.ccm.Snapstars.permission.C2D_MESSAGE"/>
<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

<uses-configuration android:reqFiveWayNav="true" />
<supports-screens android:normalScreens="true" />
<uses-feature android:required="true" android:name="android.hardware.touchscreen.multitouch" />
<application android:enabled="true" android:hardwareAccelerated="true" android:name="android.support.multidex.MultiDexApplication">

    <!-- OneSignal service and receiver -->
    <service android:name="com.milkmangames.extensions.android.push.GCMIntentService" />
    <receiver android:name="com.milkmangames.extensions.android.push.GCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND" >
	    <intent-filter>
			<action android:name="com.google.android.c2dm.intent.RECEIVE" />
			<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
			<category android:name="air.com.ccm.Snapstars" />
	  	</intent-filter>
	</receiver>
	
	<!-- this meta-data tag is required for GAnalytics -->					
	<meta-data android:name="com.google.android.gms.version" android:value="8487000"/>
	
	<activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
	
	<!-- FIREBASE CORE -->
	<!-- analytics -->
	<!--<receiver android:name="com.google.android.gms.measurement.AppMeasurementReceiver" android:enabled="true">
		<intent-filter>
			<action android:name="com.google.android.gms.measurement.UPLOAD"/>
		</intent-filter>
	</receiver>
	<service android:name="com.google.android.gms.measurement.AppMeasurementService" android:enabled="true" android:exported="false"/>-->
		
	<!-- common -->
	<provider android:authorities="air.com.ccm.Snapstars.firebaseinitprovider" android:name="com.google.firebase.provider.FirebaseInitProvider" android:exported="false" android:initOrder="100" />
	
	<!-- iid -->
	<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND" >
		<intent-filter>
			<action android:name="com.google.android.c2dm.intent.RECEIVE" />
			<action android:name="com.google.android.c2dm.intent.REGISTRATION" />
			<category android:name="air.com.ccm.Snapstars" />
		</intent-filter>
	</receiver>
	<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />
	<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
		<intent-filter android:priority="-500">
			<action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
		</intent-filter>
	</service>

  <activity android:launchMode="standard" android:excludeFromRecents="false">
    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
    </intent-filter>
    <intent-filter>
      <action android:name="android.intent.action.VIEW" />
      <category android:name="android.intent.category.DEFAULT" />
      <category android:name="android.intent.category.BROWSABLE" />
      <data android:scheme="socialme" />
    </intent-filter>
  </activity>
  <provider android:name="com.milkmangames.extensions.android.goviral.AttachedFileProvider" android:authorities="air.com.ccm.Snapstars.AttachedFileProvider" android:enabled="true" android:exported="false" android:grantUriPermissions="true" />
  <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="fb444661062410012" />
  <meta-data android:name="com.facebook.sdk.ApplicationName" android:value="NextPLZ" />
  <activity android:name="com.facebook.FacebookActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="NextPLZ" />
  <provider android:authorities="com.facebook.app.FacebookContentProvider444661062410012" android:name="com.facebook.FacebookContentProvider" android:exported="true" />
</application>
</manifest>]]></manifestAdditions>
```

**Comment by alamboley** [comment]
Oups forgotten to add com.distriqt.androidsupport.V4.ane...

**Comment by marchbold** [comment]
Glad you found the issue, hadn't seen that error before.
