### ISSUE TITLE
SIGNIN_WITH_CREDENTIAL_COMPLETE event is never dispatched.

### ISSUE THREAD

**Issue by aram-ahak** [distriqt/ANE-Firebase#156]
Hi guys.
We are using:

- Platform: Android
- Adobe Air 30.
- FirebaseAuth  version 2.1.055
- Firebase version 2.1.055
- Core version 3.2.188
- androidsupport.V4 version 27.0.2
- playservices.Base version 15.0.1

After updating ANEs, on android devices SIGNIN_WITH_CREDENTIAL_COMPLETE event is never dispatched.

The code:
```
 public function facebookAuth(accessToken:String, callback:Function):void {
        var service:FirebaseAuth = FirebaseAuth.service;
        var authCredential:AuthCredential  =FacebookAuthProvider.getCredential( accessToken );
        service.addEventListener(FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE, signInWithCredentialCompleteHandler);
        service.signInWithCredential(authCredential);

        function signInWithCredentialCompleteHandler(event:FirebaseAuthEvent):void {
            service.removeEventListener(FirebaseAuthEvent.SIGNIN_WITH_CREDENTIAL_COMPLETE, signInWithCredentialCompleteHandler);
            if (service.isSignedIn()) {
                callback(buildAuthSuccessCallback());
            }
            else {
                callback({isSuccessful: false});
            }
        }
    }
```
in manifest I added this part:
```
  <activity
        android:name="com.google.firebase.auth.internal.FederatedSignInActivity"
        android:excludeFromRecents="true"
        android:exported="true"
        android:launchMode="singleInstance"
        android:permission="com.google.firebase.auth.api.gms.permission.LAUNCH_FEDERATED_SIGN_IN"
        android:theme="@android:style/Theme.Translucent.NoTitleBar" />

```
Logcat output:
```
06-15 17:17:25.006  9051  9051 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.firebase.auth.FirebaseAuth.addAuthStateListener(com.google.firebase.auth.FirebaseAuth$AuthStateListener)' on a null object reference: air.com.plexonic.meln2
06-15 17:17:25.006  9051  9051 W System.err: 	at com.distriqt.extension.firebase.auth.controller.FirebaseAuthController.<init>(FirebaseAuthController.java:71): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at com.distriqt.extension.firebase.auth.AuthContext.controller(AuthContext.java:188): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at com.distriqt.extension.firebase.auth.functions.SignInWithCredentialFunction.call(SignInWithCredentialFunction.java:42): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at com.adobe.air.customHandler.callTimeoutFunction(Native Method): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at com.adobe.air.customHandler.handleMessage(customHandler.java:22): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at android.os.Looper.loop(Looper.java:154): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at java.lang.reflect.Method.invoke(Native Method): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496): air.com.plexonic.meln2
06-15 17:17:25.007  9051  9051 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386): air.com.plexonic.meln2
06-15 17:17:25.086  9051  9051 I air.com.plexonic.meln2: Error #2044: Unhandled error:. text=Attempt to invoke virtual method 'void com.google.firebase.auth.FirebaseAuth.addAuthStateListener(com.google.firebase.auth.FirebaseAuth$AuthStateListener)' on a null object reference: air.com.plexonic.meln2
06-15 17:17:25.127  9051  9051 I am_on_stop_called: [0,com.facebook.FacebookActivity,destroy]: air.com.plexonic.meln2
06-15 17:17:25.129  9051  9051 D ViewRootImpl@6f55fad[FacebookActivity]: dispatchDetachedFromWindow: air.com.plexonic.meln2
06-15 17:17:25.134  2399  3618 I SurfaceFlinger: id=2068 Removed air.com.plexonic.meln2/com.facebook.FacebookActivity (7/9): /system/bin/surfaceflinger
06-15 17:17:25.134  2399  2486 I SurfaceFlinger: id=2068 Removed air.com.plexonic.meln2/com.facebook.FacebookActivity (-2/9): /system/bin/surfaceflinger
06-15 17:17:25.139  9051  9051 D InputTransport: Input channel destroyed: fd=50: air.com.plexonic.meln2
06-15 17:17:25.147  2399  2399 I sf_frame_dur: [air.com.plexonic.meln2/com.facebook.FacebookActivity,2,0,6,0,0,0,0]: /system/bin/surfaceflinger
```

**Comment by david-daal** [comment]
HI @marchbold, any news on this issue?

**Comment by marchbold** [comment]
Can you post your complete manifest additions? That error seems to indicate an issue with retrieving the FirebaseAuth implementation.

**Comment by aram-ahak** [comment]
```
 <extensions>
        <extensionID>com.distriqt.Notifications</extensionID>
        <extensionID>com.distriqt.ApplicationRater</extensionID>
        <extensionID>com.distriqt.Application</extensionID>
        <extensionID>com.distriqt.NetworkInfo</extensionID>
        <extensionID>com.distriqt.Dialog</extensionID>
        <extensionID>com.distriqt.FacebookAPI</extensionID>
        <extensionID>com.distriqt.Bolts</extensionID>
        <extensionID>com.distriqt.Core</extensionID>
        <extensionID>com.distriqt.Firebase</extensionID>
        <extensionID>com.distriqt.firebase.Auth</extensionID>
        <extensionID>com.distriqt.firebase.Database</extensionID>
        <extensionID>com.distriqt.CustomResources</extensionID>
        <extensionID>com.distriqt.playservices.Base</extensionID>
        <extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
        <extensionID>com.distriqt.androidsupport.V4</extensionID>
        <extensionID>com.distriqt.androidsupport.CustomTabs</extensionID>
        <extensionID>com.distriqt.androidsupport.CardViewV7</extensionID>
        <extensionID>com.distriqt.InAppBilling</extensionID>
    </extensions>
<android>
        <manifestAdditions>
            <![CDATA[
            <manifest android:installLocation="auto">
                <uses-feature android:glEsVersion="0x00030000" android:required="true" />
                <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="27" />
                <supports-screens>
                    android:smallScreens="false"
                    android:normalScreens="true"
                    android:largeScreens="true"
                    android:xlargeScreens="true"
                </supports-screens>
           
                <uses-permission android:name="com.sec.android.provider.badge.permission.READ"/>
                <uses-permission android:name="com.sec.android.provider.badge.permission.WRITE"/>

                <uses-permission android:name="com.htc.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.htc.launcher.permission.UPDATE_SHORTCUT"/>

                <uses-permission android:name="com.sonyericsson.home.permission.BROADCAST_BADGE"/>
                <uses-permission android:name="com.sonymobile.home.permission.PROVIDER_INSERT_BADGE"/>

                <uses-permission android:name="com.anddoes.launcher.permission.UPDATE_COUNT"/>

                <uses-permission android:name="com.majeur.launcher.permission.UPDATE_BADGE"/>

                <uses-permission android:name="com.huawei.android.launcher.permission.CHANGE_BADGE"/>
                <uses-permission android:name="com.huawei.android.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.huawei.android.launcher.permission.WRITE_SETTINGS"/>

                <uses-permission android:name="android.permission.READ_APP_BADGE"/>
                <uses-permission android:name="com.oppo.launcher.permission.READ_SETTINGS"/>
                <uses-permission android:name="com.oppo.launcher.permission.WRITE_SETTINGS"/>

                <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_READ"/>
                <uses-permission android:name="me.everything.badger.permission.BADGE_COUNT_WRITE"/>

                <uses-permission android:name="android.permission.INTERNET"/>
                <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
                <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
                <uses-permission android:name="com.android.vending.BILLING" />
                <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
                <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

                <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
                <uses-permission android:name="android.permission.WAKE_LOCK" />

                <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
                <permission android:name="air.com.AppId.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
                <uses-permission android:name="air.com.AppId.permission.C2D_MESSAGE"/>

                 <application android:enabled="true" android:debuggable="false" android:allowBackup="false" android:hardwareAccelerated="false" android:name="android.support.multidex.MultiDexApplication">

                    <activity android:launchMode="singleTop" android:resizeableActivity="false">
                    android:name="com.distriqt.extension.inappbilling.activities.ProductViewActivity"
				    android:theme="@android:style/Theme.Translucent.NoTitleBar">
                        <intent-filter>
						    <action android:name="android.intent.action.MAIN"/>
						    <category android:name="android.intent.category.LAUNCHER"/>
						</intent-filter>
						<intent-filter>
						    <action android:name="android.intent.action.VIEW" />
						    <category android:name="android.intent.category.DEFAULT" />
						    <category android:name="android.intent.category.BROWSABLE" />
						    <data android:scheme="com.AppId" />
						</intent-filter>
					</activity>
					<provider
			            android:authorities="air.com.AppId.firebaseinitprovider"
                            android:name="com.google.firebase.provider.FirebaseInitProvider"
                            android:exported="false"
                            android:initOrder="100" />
                    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" android:permission="com.google.android.c2dm.permission.SEND" >
                        <intent-filter>
                            <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                            <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                            <category android:name="air.com.AppId" />
                        </intent-filter>
                    </receiver>
                    <receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false" />

                    <service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
                        <intent-filter android:priority="-500">
                            <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
                        </intent-filter>
                    </service>

                    <activity android:name="com.google.android.gms.common.api.GoogleApiActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:exported="false"/>
                    <activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="Pet Savers" />
                    <activity android:name="com.facebook.CustomTabMainActivity" />
                    <activity android:name="com.facebook.CustomTabActivity" android:exported="true" >
                        <intent-filter>
                            <action android:name="android.intent.action.VIEW" />
                            <category android:name="android.intent.category.DEFAULT" />
                            <category android:name="android.intent.category.BROWSABLE" />
                            <data android:scheme="fbFbApplicationId" />
                        </intent-filter>
                    </activity>
                    <activity android:name="com.facebook.LoginActivity" android:theme="@android:style/Theme.Translucent.NoTitleBar" android:label="Login" />
                    <activity
                            android:name="com.google.firebase.auth.internal.FederatedSignInActivity"
                            android:excludeFromRecents="true"
                            android:exported="true"
                            android:launchMode="singleInstance"
                            android:permission="com.google.firebase.auth.api.gms.permission.LAUNCH_FEDERATED_SIGN_IN"
                            android:theme="@android:style/Theme.Translucent.NoTitleBar" />

                    <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
					<meta-data android:name="com.facebook.sdk.ApplicationName" android:value="Pet Savers"/>
					<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="\ FbApplicationId"/>

                    <provider android:authorities="com.facebook.app.FacebookContentProviderFbApplicationId" android:name="com.facebook.FacebookContentProvider" android:exported="true" />
                    <receiver android:name="com.distriqt.extension.notifications.notifications.receivers.NotificationReceiver">
				<intent-filter>
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_SELECTED" />
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_DELETED" />
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_ACTION" />
					<action android:name="APPLICATION_PACKAGE.NOTIFICATION_DELAYED" />
					<data android:scheme="dtn" />
				</intent-filter>
				<intent-filter>
					<action android:name="android.intent.action.BOOT_COMPLETED" />
				</intent-filter>
			</receiver>
			<provider
				android:name="android.support.v4.content.FileProvider"
				android:authorities="APPLICATION_PACKAGE.fileprovider"
				android:grantUriPermissions="true"
				android:exported="false">
				<meta-data
					android:name="android.support.FILE_PROVIDER_PATHS"
					android:resource="@xml/distriqt_notifications_paths" />
			</provider>

			<provider android:name="android.arch.lifecycle.ProcessLifecycleOwnerInitializer" android:authorities="APPLICATION_PACKAGE.lifecycle-trojan" android:multiprocess="true"/>

				</application>
            </manifest>
            ]]>
        </manifestAdditions>
</android>
```

**Comment by marchbold** [comment]
Ah looks as though you are missing several of the Firebase core manifest additions: https://github.com/distriqt/ANE-Firebase/wiki/Core---Add-the-extensions

```xml
<!-- FIREBASE CORE -->
<!-- common -->
<service android:name="com.google.firebase.components.ComponentDiscoveryService" >
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.auth.FirebaseAuthRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.analytics.connector.internal.AnalyticsConnectorRegistrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
    <meta-data
        android:name="com.google.firebase.components:com.google.firebase.iid.Registrar"
        android:value="com.google.firebase.components.ComponentRegistrar" />
</service>
<provider
    android:authorities="YOUR_APPLICATION_PACKAGE.firebaseinitprovider"
    android:name="com.google.firebase.provider.FirebaseInitProvider"
    android:exported="false"
    android:initOrder="100" />


<!-- analytics -->
<receiver
    android:name="com.google.android.gms.measurement.AppMeasurementReceiver"
    android:enabled="true"
    android:exported="false" >
</receiver>
<receiver
    android:name="com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver"
    android:enabled="true"
    android:exported="true"
    android:permission="android.permission.INSTALL_PACKAGES" >
    <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
    </intent-filter>
</receiver>

<service
    android:name="com.google.android.gms.measurement.AppMeasurementService"
    android:enabled="true"
    android:exported="false" />
<service
    android:name="com.google.android.gms.measurement.AppMeasurementJobService"
    android:enabled="true"
    android:exported="false"
    android:permission="android.permission.BIND_JOB_SERVICE" />


<!-- iid -->
<receiver
    android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
    android:exported="true"
    android:permission="com.google.android.c2dm.permission.SEND" >
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />

        <category android:name="YOUR_APPLICATION_PACKAGE" />
    </intent-filter>
</receiver>
<!--
        FirebaseInstanceIdService performs security checks at runtime,
        no need for explicit permissions despite exported="true"
-->
<service
    android:name="com.google.firebase.iid.FirebaseInstanceIdService"
    android:exported="true" >
    <intent-filter android:priority="-500" >
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
    </intent-filter>
</service>
```

Check the example for more:

https://github.com/distriqt/ANE-Firebase/blob/master/example/auth/starling/src/TestFirebase-app.xml

**Comment by aram-ahak** [comment]
Thanks a lot. It is fixed
