### ISSUE TITLE
Not able to build APK with updated version of Firebase ANE

### ISSUE THREAD

**Issue by apofis1969** [distriqt/ANE-Firebase#189]
Hi, I updated all my ANEs. 
After doing this I received the error messages below. Packaging with AIR 32
I removed the new Firebase Ane and added the version before the update. The build worked.
maybe you have an idea which ane is creating the conflict with the new Firebase ANE
I am using the following ANEs with the App:
```
<extensions>
    <extensionID>com.distriqt.Permissions</extensionID>
    <extensionID>com.distriqt.androidsupport.CustomTabs</extensionID>
    <extensionID>com.distriqt.Dialog</extensionID>
    <extensionID>com.distriqt.playservices.Location</extensionID>
    <extensionID>com.distriqt.androidsupport.V4</extensionID>
    <extensionID>com.distriqt.Image</extensionID>
    <extensionID>com.distriqt.playservices.Analytics</extensionID>
    <extensionID>com.distriqt.PushNotifications</extensionID>
    <extensionID>com.distriqt.PDFReader</extensionID>
    <extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
    <extensionID>com.distriqt.CustomResources</extensionID>
    <extensionID>com.distriqt.Core</extensionID>
    <extensionID>com.distriqt.GoogleAnalytics</extensionID>
    <extensionID>com.distriqt.InAppBilling</extensionID>
    <extensionID>com.distriqt.NetworkInfo</extensionID>
    <extensionID>com.distriqt.playservices.Base</extensionID>
    <extensionID>com.distriqt.Application</extensionID>
    <extensionID>com.distriqt.Firebase</extensionID>
  </extensions>
 ```
##### Expected behaviour
Creating APK.

##### Actual behaviour
```
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/measurement/zzec;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/internal/measurement/zzdx;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/firebase/analytics/FirebaseAnalytics$Event;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
3 errors; aborting
```
##### Environment 

- AIR SDK version: 32
- Device OS: 
- Device version: 
- Development IDE: 
- Development OS:

##### Logs

Device logs if relevant

**Comment by marchbold** [comment]
When updating Firebase you need to make sure you update all Google related ANEs as well, in particular the Google Play Services ANEs. If you don't you will likely run into issues like this.

**Comment by apofis1969** [comment]
I am using: 
Google PlayServices v. 16.0.5
Google Analytics [v2.0.028]

**Comment by marchbold** [comment]
What IDE are you using, it may be caching an older version of the ANEs?

**Comment by apofis1969** [comment]
No it can´t catch older versions. I am using FDT, but the ANEs are linked to the folders on my computer with the updated versions.. All older folders have been renamed.

**Comment by marchbold** [comment]
Which variant of the Push Notifications ANE are you using? 

I am struggling to come up with any other reason apart from version issues here, those errors nearly always indicate a version mismatch.

**Comment by apofis1969** [comment]
Hi, I am using the OneSignal Ane version 2018.11.27 [v7.7.284]

**Comment by apofis1969** [comment]
Hi, I did a clean project. There it worked for me as well. Have no idea where to search the bug.

**Comment by marchbold** [comment]
Definitely sounds like a caching issue then. 

I suggest clearing all FDT caches and double checking all the ANEs you have linked in your project.

**Comment by apofis1969** [comment]
Hi, could fix. was obviously a problem with cache. Thanks. 
Best regards
Johannes
