### ISSUE TITLE
FireStore crash

### ISSUE THREAD

**Issue by jasonJamEther** [distriqt/ANE-Firebase#211]
Not sure if this is a bug or user error. I am using the Firebase ANE and have been using some of it's features like storage for awhile. I just added in firestore. The app opens and firestore initializes fine. I have an interaction which submits a collection to firestore. As soon as I call - document.setDocument( changes ); the app crashes. I have supplied the code block as well as the system logs. I do see it pointing out some warnings like "the behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK."

##### Code

```as3
if(FirebaseFirestore.isSupported)
			{
				var document:DocumentReference = FirebaseFirestore.service.collection( "users" ).document( userID );
				document.addEventListener( DocumentReferenceEvent.SET_SUCCESS, ane_successHandler );
				document.addEventListener( DocumentReferenceEvent.SET_ERROR, ane_errorHandler );
				
				var changes:Object = {"challenges":  allJoinedChallenges};
				document.setDocument( changes );
			}
```

##### Expected behaviour

document.setDocument( changes ) submits changes to firestore database

##### Actual behaviour

Application crashes

##### Environment 

- AIR SDK version:  Air 32
- Device OS: Samsung Galaxy S7
- Device version: Android 8.0
- Development IDE: Adobe Animate
- Development OS: Mac OS Mojave 10.14.3

##### Logs

```
03-25 10:24:54.912  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::collection( users )
03-25 10:24:54.917  2492  2492 W Firestore: (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
03-25 10:24:54.917  2492  2492 W Firestore: To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
03-25 10:24:54.917  2492  2492 W Firestore:
03-25 10:24:54.917  2492  2492 W Firestore: FirebaseFirestore firestore = FirebaseFirestore.getInstance();
03-25 10:24:54.917  2492  2492 W Firestore: FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
03-25 10:24:54.917  2492  2492 W Firestore:     .setTimestampsInSnapshotsEnabled(true)
03-25 10:24:54.917  2492  2492 W Firestore:     .build();
03-25 10:24:54.917  2492  2492 W Firestore: firestore.setFirestoreSettings(settings);
03-25 10:24:54.917  2492  2492 W Firestore:
03-25 10:24:54.917  2492  2492 W Firestore: With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
03-25 10:24:54.917  2492  2492 W Firestore:
03-25 10:24:54.917  2492  2492 W Firestore: // Old:
03-25 10:24:54.917  2492  2492 W Firestore: java.util.Date date = snapshot.getDate("created_at");
03-25 10:24:54.917  2492  2492 W Firestore: // New:
03-25 10:24:54.917  2492  2492 W Firestore: Timestamp timestamp = snapshot.getTimestamp("created_at");
03-25 10:24:54.917  2492  2492 W Firestore: java.util.Date date = timestamp.toDate();
03-25 10:24:54.917  2492  2492 W Firestore:
03-25 10:24:54.917  2492  2492 W Firestore: Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
03-25 10:24:54.919  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::identifierForCollection: new reference: 25b788d0-dddf-42ba-b8c7-0f1f4c119aab
03-25 10:24:54.922  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::collection_document( 25b788d0-dddf-42ba-b8c7-0f1f4c119aab, jRs3EmwQIwfPeoPmAld3QAwXBSx1 )
03-25 10:24:54.922  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::collectionByIdentifier( 25b788d0-dddf-42ba-b8c7-0f1f4c119aab )
03-25 10:24:54.924  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::identifierForDocument: new reference: dd78be18-5015-44e4-a073-dc3e81dbce3f
03-25 10:24:54.927  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::document_addEventListener( dd78be18-5015-44e4-a073-dc3e81dbce3f, set:success )
03-25 10:24:54.927  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::documentByIdentifier( dd78be18-5015-44e4-a073-dc3e81dbce3f )
03-25 10:24:54.929  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::document_addEventListener( dd78be18-5015-44e4-a073-dc3e81dbce3f, set:error )
03-25 10:24:54.930  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::documentByIdentifier( dd78be18-5015-44e4-a073-dc3e81dbce3f )
03-25 10:24:54.932  2492  2492 D com.distriqt.firebase.Firestore: JSONUtils::toMap( {"challenges":[{"currentCheckpoint":0,"challenge":"projects\/gofoto-d3a4e\/databases\/(default)\/documents\/challenges\/NUtpileq5O55GxLgqbNh"}]} )
03-25 10:24:54.932  2492  2492 D com.distriqt.firebase.Firestore: JSONUtils::toJavaValue( JSONArray )
03-25 10:24:54.932  2492  2492 D com.distriqt.firebase.Firestore: JSONUtils::toJavaValue( JSONObject )
03-25 10:24:54.932  2492  2492 D com.distriqt.firebase.Firestore: JSONUtils::toMap( {"currentCheckpoint":0,"challenge":"projects\/gofoto-d3a4e\/databases\/(default)\/documents\/challenges\/NUtpileq5O55GxLgqbNh"} )
03-25 10:24:54.933  2492  2492 D com.distriqt.firebase.Firestore: JSONUtils::toJavaValue( Integer )
03-25 10:24:54.933  2492  2492 D com.distriqt.firebase.Firestore: JSONUtils::toJavaValue( String )
03-25 10:24:54.933  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::document_set( dd78be18-5015-44e4-a073-dc3e81dbce3f )
03-25 10:24:54.940  2492  2658 I zygote  : find the special shared library, skip check
03-25 10:24:54.945  2492  2658 I zygote  : find the special shared library, skip check
03-25 10:24:54.964  2492  2492 D InputMethodManager: HSIFW - flag : 0 Pid : 2492
03-25 10:24:54.965  1545  2786 V InputMethodManagerService: Client requesting input be hidden, flags : 0
03-25 10:24:54.965  1545  2786 V InputMethodManagerService: hideCurrentInputLocked : shouldHideSoftInput is false
03-25 10:24:54.985  2492  2492 D com.distriqt.firebase.Firestore: FirestoreController::documentByIdentifier( dd78be18-5015-44e4-a073-dc3e81dbce3f )
03-25 10:24:55.123  2492  2658 V NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
03-25 10:24:55.177   733   733 I android.hardware.wifi@1.0-service: getLinkLayerStats
03-25 10:24:55.197  2492  2658 I ProviderInstaller: Installed default security provider GmsCore_OpenSSL
03-25 10:24:55.232  2492  2492 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-25 10:24:55.236  2492  2492 E AndroidRuntime: FATAL EXCEPTION: main
03-25 10:24:55.236  2492  2492 E AndroidRuntime: Process: air.com.gofotoapp.gofoto, PID: 2492
03-25 10:24:55.236  2492  2492 E AndroidRuntime: java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@17.1.3:377)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(Unknown Source:2)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6944)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
03-25 10:24:55.236  2492  2492 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/ConnectionSpec$Builder;
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelBuilder.<clinit>(OkHttpChannelBuilder.java:80)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelBuilder.forTarget(OkHttpChannelBuilder.java:137)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:48)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:27)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:70)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.remote.Datastore.<init>(com.google.firebase:firebase-firestore@@17.1.3:101)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@17.1.3:216)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@17.1.3:108)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(Unknown Source:8)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@17.1.3:309)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(Unknown Source:2)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@17.1.3:285)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(Unknown Source:4)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@17.1.3:203)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
03-25 10:24:55.236  2492  2492 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.ConnectionSpec$Builder" on path: DexPathList[[zip file "/data/app/air.com.gofotoapp.gofoto-O8gS-46iJhSz4HPLJjglUA==/base.apk"],nativeLibraryDirectories=[/data/app/air.com.gofotoapp.gofoto-O8gS-46iJhSz4HPLJjglUA==/lib/arm, /data/app/air.com.gofotoapp.gofoto-O8gS-46iJhSz4HPLJjglUA==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
03-25 10:24:55.236  2492  2492 E AndroidRuntime:        ... 20 more
```

**Comment by marchbold** [comment]
Can you tell us what is in the data you are saving?

**Comment by jasonJamEther** [comment]
For the sake of testing I went ahead and adjusted my code base to match the wiki example. It resulted in the same crash.
`
var document:DocumentReference = FirebaseFirestore.service.collection( "users" ).document( "test" );
document.addEventListener( DocumentReferenceEvent.SET_SUCCESS, ane_successHandler );
document.addEventListener( DocumentReferenceEvent.SET_ERROR, ane_errorHandler );
				
var city:Object = {
    name: "Los Angeles",
    state: "CA",
    country:  "USA"
};
				
document.setDocument( city );`

**Comment by marchbold** [comment]
Could you try adding the okhttp ANE:

https://github.com/distriqt/ANE-SquareLibs

I'm not sure how but it seems we have missed this dependency from the docs.

**Comment by jasonJamEther** [comment]
That solved it! Glad it was such an easy fix. Thank you for the solution.

**Comment by marchbold** [comment]
Great to hear! I'll make sure we get the documentation updated...
