### ISSUE TITLE
Android crash - DocumentReference.setDocument in Firestore

### ISSUE THREAD

**Issue by arcreature7** [distriqt/ANE-Firebase#228]
Hi,

I applied all ane modified to 64 bit and did build with AIR 33.
But the application crashes in Firebase.
This issue is the same as closed "FireStore crash # 211".

Previously, the same issue was solved by including com.distriqt.square.okhttp.ane.
However, com.distriqt.square.okhttp.ane does not currently support 64-bit.
How do I solve this problem?

I'm in a situation where I need to solve this problem very quickly.
I need your help desperately.

##### Expected behaviour
DocumentReference.setDocument(data);

##### Actual behaviour
Application crashes

##### Environment 

- AIR SDK version: 
- Device OS: AIR 33
- Device version: Samsung Galaxy S8
- Development IDE: FlashDevelop
- Development OS: Windows 10

##### Logs
```
D com.distriqt.firebase.Firestore: FirestoreController::document( androidUsers/USERID )
08-13 06:20:57.530 18789 18789 W Firestore: (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
08-13 06:20:57.530 18789 18789 W Firestore: To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
08-13 06:20:57.530 18789 18789 W Firestore:
08-13 06:20:57.530 18789 18789 W Firestore: FirebaseFirestore firestore = FirebaseFirestore.getInstance();
08-13 06:20:57.530 18789 18789 W Firestore: FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
08-13 06:20:57.530 18789 18789 W Firestore:     .setTimestampsInSnapshotsEnabled(true)
08-13 06:20:57.530 18789 18789 W Firestore:     .build();
08-13 06:20:57.530 18789 18789 W Firestore: firestore.setFirestoreSettings(settings);
08-13 06:20:57.530 18789 18789 W Firestore:
08-13 06:20:57.530 18789 18789 W Firestore: With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
08-13 06:20:57.530 18789 18789 W Firestore:
08-13 06:20:57.530 18789 18789 W Firestore: // Old:
08-13 06:20:57.530 18789 18789 W Firestore: java.util.Date date = snapshot.getDate("created_at");
08-13 06:20:57.530 18789 18789 W Firestore: // New:
08-13 06:20:57.530 18789 18789 W Firestore: Timestamp timestamp = snapshot.getTimestamp("created_at");
08-13 06:20:57.530 18789 18789 W Firestore: java.util.Date date = timestamp.toDate();
08-13 06:20:57.530 18789 18789 W Firestore:
08-13 06:20:57.530 18789 18789 W Firestore: Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
08-13 06:20:57.531 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::identifierForDocument: new reference: e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0
08-13 06:20:57.534 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::document_addEventListener( e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0, get:success )
08-13 06:20:57.534 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::documentByIdentifier( e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0 )
08-13 06:20:57.535 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::document_addEventListener( e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0, get:error )
08-13 06:20:57.535 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::documentByIdentifier( e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0 )
08-13 06:20:57.536 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::document_get( e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0, null )
08-13 06:20:57.539 18789 19096 V NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
08-13 06:20:57.541 18789 18789 D com.distriqt.firebase.RemoteConfig: RemoteConfigController::fetch( 0 )
08-13 06:20:57.548  3748 21381 D CompatibilityInfo: mCompatibilityFlags - 0
08-13 06:20:57.548  3748 21381 D CompatibilityInfo: applicationDensity - 480
08-13 06:20:57.548  3748 21381 D CompatibilityInfo: applicationScale - 1.0
08-13 06:20:57.560 18789 19096 I ProviderInstaller: Installed default security provider GmsCore_OpenSSL
08-13 06:20:57.655 18789 18789 D com.distriqt.Firebase.Auth: FirebaseAuthController::onAuthStateChanged(): signed in
08-13 06:20:57.655 18789 18789 D com.distriqt.firebase.Firestore: FirestoreController::documentByIdentifier( e3f0d7cc-9cc0-4fa9-8561-092bf6c74fd0 )
08-13 06:20:57.656 18789 18789 W Firestore: (0.6.6-dev) [AsyncQueue]: Refused to enqueue task after panic
08-13 06:20:57.657 18789 18789 D AndroidRuntime: Shutting down VM
08-13 06:20:57.657 18789 18789 E AndroidRuntime: FATAL EXCEPTION: main
08-13 06:20:57.657 18789 18789 E AndroidRuntime: Process: com.arcgamestudio.zombiesweeper, PID: 18789
08-13 06:20:57.657 18789 18789 E AndroidRuntime: java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$5(com.google.firebase:firebase-firestore@@17.1.3:377)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run(com.google.firebase:firebase-firestore@@17.1.3)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6776)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
08-13 06:20:57.657 18789 18789 E AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/ConnectionSpec$Builder;
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelBuilder.<clinit>(OkHttpChannelBuilder.java:80)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelBuilder.forTarget(OkHttpChannelBuilder.java:137)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:48)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:27)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:70)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.remote.Datastore.<init>(com.google.firebase:firebase-firestore@@17.1.3:101)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.core.FirestoreClient.initialize(com.google.firebase:firebase-firestore@@17.1.3:216)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.core.FirestoreClient.lambda$new$2(com.google.firebase:firebase-firestore@@17.1.3:108)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.core.FirestoreClient$$Lambda$2.run(com.google.firebase:firebase-firestore@@17.1.3)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$4(com.google.firebase:firebase-firestore@@17.1.3:309)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call(com.google.firebase:firebase-firestore@@17.1.3)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue.lambda$enqueue$3(com.google.firebase:firebase-firestore@@17.1.3:285)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(com.google.firebase:firebase-firestore@@17.1.3)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run(com.google.firebase:firebase-firestore@@17.1.3:203)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:762)
08-13 06:20:57.657 18789 18789 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.ConnectionSpec$Builder" on path: DexPathList[[zip file "/data/app/com.arcgamestudio.zombiesweeper-1/base.apk"],nativeLibraryDirectories=[/data/app/com.arcgamestudio.zombiesweeper-1/lib/arm64, /data/app/com.arcgamestudio.zombiesweeper-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-13 06:20:57.657 18789 18789 E AndroidRuntime:        ... 20 more
```

**Comment by marchbold** [comment]
Apologies, we haven't published the 64bit square libs library. I'll get that up today.

**Comment by arcreature7** [comment]
Sounds good!
Thank you so much!!

**Comment by marchbold** [comment]
Square libs have been released, let me know if you are still having this issue after the update.

**Comment by arcreature7** [comment]
The crash issue was solved by applying the updated Square library.
Thank you :)
