### ISSUE TITLE
cannot package apk with the CustomResources ane

### ISSUE THREAD

**Issue by kakarlus** [distriqt/ANE-Firebase#63]
this error occurs after i try to package my app

```
aapt tool failed:invalid resource directory name: /private/var/folders/yx/51sdh4ss35jg_f27n35lmt0jrm1hqt/T/08a53880-52b3-4db5-8ca6-4e90655cca09/distriqt-extension-customresources-res values.xml
```

my ant build was successful though, here are the logs
```
Buildfile: /Users/jacarlos/Downloads/ANE-Firebase-master/config/build.xml

clean:

clean_actionscript:
   [delete] Deleting directory /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/actionscript/bin

clean_default:
   [delete] Deleting directory /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/default/bin

clean_android:
   [delete] Deleting: /Users/jacarlos/Downloads/ANE-Firebase-master/config/build_config/platform_android.build.xml
   [delete] Deleting directory /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/build
   [delete] Deleting directory /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app

build:

build_actionscript:
     [echo] Building actionscript library...
    [compc] Loading configuration: /Users/jacarlos/Documents/AIRSDK25nc/frameworks/air-config.xml
    [compc] 
    [compc] 2172 bytes written to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/actionscript/bin/distriqt.extension.resources.swc in 0.704 seconds
     [echo] done

build_default:
     [echo] Building default library...
    [compc] Loading configuration: /Users/jacarlos/Documents/AIRSDK25nc/frameworks/air-config.xml
    [compc] 
    [compc] 2015 bytes written to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/default/bin/distriqt.extension.resources.default.swc in 0.481 seconds
     [echo] done

create_android_project:
    [mkdir] Created dir: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app
     [copy] Copying 4 files to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app
    [mkdir] Created dir: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app/src/main/java/com/distriqt/extension/customresources
     [copy] Copying 2 files to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app/src/main/java/com/distriqt/extension/customresources
    [mkdir] Created dir: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app/src/main/res
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app/src/main/res
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/app/libs

build_android:
     [echo] Building Android library...

build_android_osx:
     [exec] Incremental java compilation is an incubating feature.
     [exec] :wrapper UP-TO-DATE
     [exec] 
     [exec] BUILD SUCCESSFUL
     [exec] 
     [exec] Total time: 4.555 secs
     [exec] 
     [exec] This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
     [exec] Incremental java compilation is an incubating feature.
     [exec] :app:preBuild UP-TO-DATE
     [exec] :app:preDebugBuild UP-TO-DATE
     [exec] :app:checkDebugManifest
     [exec] :app:prepareDebugDependencies
     [exec] :app:compileDebugAidl
     [exec] :app:compileDebugNdk UP-TO-DATE
     [exec] :app:compileLint
     [exec] :app:copyDebugLint UP-TO-DATE
     [exec] :app:mergeDebugShaders
     [exec] :app:compileDebugShaders
     [exec] :app:generateDebugAssets
     [exec] :app:mergeDebugAssets
     [exec] :app:mergeDebugProguardFiles UP-TO-DATE
     [exec] :app:packageDebugRenderscript UP-TO-DATE
     [exec] :app:compileDebugRenderscript
     [exec] :app:generateDebugResValues
     [exec] :app:generateDebugResources
     [exec] :app:packageDebugResources
     [exec] :app:processDebugManifest
     [exec] :app:generateDebugBuildConfig
     [exec] :app:processDebugResources
     [exec] :app:generateDebugSources
     [exec] :app:incrementalDebugJavaCompilationSafeguard
     [exec] :app:compileDebugJavaWithJavac
     [exec] :app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
     [exec] :app:processDebugJavaRes UP-TO-DATE
     [exec] :app:transformResourcesWithMergeJavaResForDebug
     [exec] :app:transformClassesAndResourcesWithSyncLibJarsForDebug
     [exec] :app:mergeDebugJniLibFolders
     [exec] :app:transformNative_libsWithMergeJniLibsForDebug
     [exec] :app:transformNative_libsWithSyncJniLibsForDebug
     [exec] :app:bundleDebug
     [exec] :app:compileDebugSources
     [exec] :app:assembleDebug
     [exec] :app:preReleaseBuild UP-TO-DATE
     [exec] :app:checkReleaseManifest
     [exec] :app:prepareReleaseDependencies
     [exec] :app:compileReleaseAidl
     [exec] :app:compileReleaseNdk UP-TO-DATE
     [exec] :app:copyReleaseLint UP-TO-DATE
     [exec] :app:mergeReleaseShaders
     [exec] :app:compileReleaseShaders
     [exec] :app:generateReleaseAssets
     [exec] :app:mergeReleaseAssets
     [exec] :app:mergeReleaseProguardFiles UP-TO-DATE
     [exec] :app:packageReleaseRenderscript UP-TO-DATE
     [exec] :app:compileReleaseRenderscript
     [exec] :app:generateReleaseResValues
     [exec] :app:generateReleaseResources
     [exec] :app:packageReleaseResources
     [exec] :app:processReleaseManifest
     [exec] :app:generateReleaseBuildConfig
     [exec] :app:processReleaseResources
     [exec] :app:generateReleaseSources
     [exec] :app:incrementalReleaseJavaCompilationSafeguard
     [exec] :app:compileReleaseJavaWithJavac
     [exec] :app:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
     [exec] :app:processReleaseJavaRes UP-TO-DATE
     [exec] :app:transformResourcesWithMergeJavaResForRelease
     [exec] :app:transformClassesAndResourcesWithSyncLibJarsForRelease
     [exec] :app:mergeReleaseJniLibFolders
     [exec] :app:transformNative_libsWithMergeJniLibsForRelease
     [exec] :app:transformNative_libsWithSyncJniLibsForRelease
     [exec] :app:bundleRelease
     [exec] :app:compileReleaseSources
     [exec] :app:assembleRelease
     [exec] :app:assemble
     [exec] 
     [exec] BUILD SUCCESSFUL
     [exec] 
     [exec] Total time: 4.76 secs
     [exec] 
     [exec] This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html

build_android_windows:

package:

package_android:
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/build
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/build/distriqt-extension-customresources-res

setup_platform_options_android:
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/build_config
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/build_config
    [mkdir] Created dir: /Users/jacarlos/Downloads/ANE-Firebase-master/config/.tmp
    [unzip] Expanding: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/actionscript/bin/distriqt.extension.resources.swc into /Users/jacarlos/Downloads/ANE-Firebase-master/config/.tmp
     [copy] Copying 1 file to /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/build
   [delete] Deleting directory /Users/jacarlos/Downloads/ANE-Firebase-master/config/.tmp
    [unzip] Expanding: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/default/bin/distriqt.extension.resources.default.swc into /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/default/bin
   [delete] Deleting: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/default/bin/catalog.xml

compile_windows:

compile_osx:
   [delete] Deleting: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/android/build/library.swf
   [delete] Deleting: /Users/jacarlos/Downloads/ANE-Firebase-master/config/platform/default/bin/library.swf

all:

BUILD SUCCESSFUL
```

thanks in advance! :)

**Comment by marchbold** [comment]
When exactly is that error being shown? When you are packaging with AIR?

What version of AIR are you using?

**Comment by kptac** [comment]
Ant 1.10.1
jdk1.8.0_131
Air 26
Latest Android SDK

```
>ant
Buildfile: C:\Users\Debug\Desktop\config\build.xml

clean:

clean_actionscript:

clean_default:

clean_android:

build:

build_actionscript:
     [echo] Building actionscript library...
    [compc] Loading configuration: C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\4.6.0\frameworks\air-config.xml
    [compc]
    [compc]
    [compc] 2172 bytes written to C:\Users\Debug\Desktop\config\platform\actionscript\bin\distriqt.extension.config.swc in 0.777 seconds
    [compc]
     [echo] done

build_default:
     [echo] Building default library...
    [compc] Loading configuration: C:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\sdks\4.6.0\frameworks\air-config.xml
    [compc]
    [compc]
    [compc] 2016 bytes written to C:\Users\Debug\Desktop\config\platform\default\bin\distriqt.extension.config.default.swc in 0.669 seconds
    [compc]
     [echo] done

create_android_project:
    [mkdir] Created dir: C:\Users\Debug\Desktop\config\platform\android\app
     [copy] Copying 4 files to C:\Users\Debug\Desktop\config\platform\android\app
    [mkdir] Created dir: C:\Users\Debug\Desktop\config\platform\android\app\src\main\java\com\mapinn\mycardmap
     [copy] Copying 2 files to C:\Users\Debug\Desktop\config\platform\android\app\src\main\java\com\mapinn\mycardmap
    [mkdir] Created dir: C:\Users\Debug\Desktop\config\platform\android\app\src\main\res
     [copy] Copying 1 file to C:\Users\Debug\Desktop\config\platform\android\app\src\main\res
     [copy] Copying 1 file to C:\Users\Debug\Desktop\config\platform\android
     [copy] Copying 1 file to C:\Users\Debug\Desktop\config\platform\android\app\libs

build_android:
     [echo] Building Android library...

build_android_osx:

build_android_windows:

BUILD FAILED
C:\Users\Debug\Desktop\config\build.xml:215: The following error occurred while executing this line:
C:\Users\Debug\Desktop\config\build.xml:146: The following error occurred while executing this line:
C:\Users\Debug\Desktop\config\build.xml:163: Execute failed: java.io.IOException: Cannot run program "gradlew.bat" (in directory "C:\Users\Debug\Desktop\config\platform\android"): CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:426)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:440)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:629)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:670)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:496)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
        at java.lang.ProcessImpl.start(ProcessImpl.java:137)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 49 more

Total time: 2 seconds


```

**Comment by kptac** [comment]
Following are the environment variables:

ANT_HOME = C:\apache-ant\apache-ant-1.10.1
JAVA_HOME = C:\Program Files\Java\jdk1.8.0_131
JRE_HOME = C:\Program Files\Java\jre1.8.0_131

Amended Path variable with: %JAVA_HOME%\bin;%JRE_HOME%\bin

**Comment by kakarlus** [comment]
im using Version 25.0.0.134, the error occurs when i  run `adt` to package my app

**Comment by marchbold** [comment]
@kptac That looks like a different issue, can you please post the details in a separate issue.

@kakarlus Can you list what ANEs you are using? Any change you have 2 custom resource anes in your extensions directory?

**Comment by kakarlus** [comment]
@marchbold here's what i have, no duplicates of custom resources 
![screen shot 2017-05-31 at 4 08 12 pm](https://cloud.githubusercontent.com/assets/809310/26621985/59e1e03a-461b-11e7-979e-3a7d93965758.png)

**Comment by marchbold** [comment]
Okay I'm going to check in a small update to change that directory name to something simpler. Can you try the update?

**Comment by kakarlus** [comment]
which files do i need to update?

**Comment by marchbold** [comment]
Just update the custom resources repository?

https://github.com/distriqt/ANE-CustomResources/

**Comment by kakarlus** [comment]
Sorry but it's having the same error

```
aapt tool failed:invalid resource directory name: /private/var/folders/yx/51sdh4ss35jg_f27n35lmt0jrm1hqt/T/10530d18-5c33-4be0-8fec-3eed07678e1c/customresources values.xml
```

i updated the customresources repo, changed the build.config, pasted my values.xml under res directory, and compiled ant. the build was successful

compiled my as files, then packaged it, the error above occured

**Comment by marchbold** [comment]
What's your targetsdk / minimum sdk for your application in your manifest additions?

**Comment by kakarlus** [comment]
23

**Comment by marchbold** [comment]
do you specify a minimum?

**Comment by kakarlus** [comment]
no, i didn't

**Comment by marchbold** [comment]
What's in your `values.xml` ? You don't have any malformed comments or something in there?

**Comment by kakarlus** [comment]
i don't think so heres my `values.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>

	<!-- Present in all applications -->
	<string name="google_app_id" translatable="false">x:xxxxxxxxx:android:xxxxxxxxx</string>

	<!-- Present in applications with the appropriate services configured -->
	<string name="gcm_defaultSenderId" translatable="false">xxxxxxxxx</string>
	<string name="default_web_client_id" translatable="false">xxxxxxxxx-xxxxxxxxxx.apps.googleusercontent.com</string>
	<!-- <string name="ga_trackingId" translatable="false">UA-65557217-3</string> -->
	<string name="firebase_database_url" translatable="false">https://xxxxxxxx.firebaseio.com/</string>
	<string name="google_storage_bucket" translatable="false">xxxxxxxx.appspot.com</string>
	<string name="google_api_key" translatable="false">xxxxxxxxxxxxxxx</string>
	<string name="google_crash_reporting_api_key" translatable="false">xxxxxxxxxxxxxxx</string>

</resources>
```

**Comment by marchbold** [comment]
Could you try removing all the comment strings? Sometimes they can cause issues.

**Comment by kakarlus** [comment]
i did that, same error unfortunately

```
aapt tool failed:invalid resource directory name: /private/var/folders/yx/51sdh4ss35jg_f27n35lmt0jrm1hqt/T/ce6f0da2-b5e9-4f20-8c33-cfed490e9ad5/customresources values.xml
```

**Comment by kakarlus** [comment]
does anyone else have the same problem with me? 😞

**Comment by marchbold** [comment]
Unfortunately we can't replicate this issue, so I'm not exactly sure what's happening for you. Could you email us (airnativeextensions@distriqt.com) the custom resources ANE you are producing and we'll see if we can replicate the issue with it?

**Comment by kakarlus** [comment]
sent, thanks again for the help

**Comment by kakarlus** [comment]
please let me know if you can replicate the issue.

**Comment by marchbold** [comment]
We have been able to replicate the issue you are having. There appears to be something wrong with the ANEs you are generating.

Try this version:

https://www.dropbox.com/s/dr9fic32tzl4rlk/com.distriqt.extension.customresources.Resources.kakarlus.zip?dl=0

**Comment by kakarlus** [comment]
@marchbold 

thanks for helping, i got the file and it packaged ok.
so where did it go wrong?

**Comment by marchbold** [comment]
I'm not sure what's occurring on your machine, something is incorrectly assembling the android code. Could you try a clean check out of the CustomResources repository and let me know what happens?

**Comment by kakarlus** [comment]
i just did. edited the build.config variables and put my values.xml under res folder and the build was successful.

packaging the app has the same error.

**Comment by marchbold** [comment]
Can you check you have the latest updates for Android Studio (including the Android SDK) and Java on your system

**Comment by kakarlus** [comment]
i have updated Android Studio and Android SDKs through Android Studio's SDK Manager (installed SDK Platforms from Android 3.0 up to Android 8.0. I have updated my Java too, same error appears.

**Comment by kakarlus** [comment]
after build is done, i only need the .ane file right?

**Comment by marchbold** [comment]
Correct, you only need the ane. What version of Java are you using?

**Comment by kakarlus** [comment]
Java 8 Update 131

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by marchbold** [comment]
What about the version of `ant` ? 

Could you try opening the project in Android Studio and see if it give you any errors?

**Comment by kakarlus** [comment]
Apache Ant(TM) version 1.10.1 compiled on February 2 2017

not sure what you mean with opening the project in Android Studio? open the ANE-CustomResources project?

btw for my app i didn't use any IDE, just a text editor and the flex/air framework. i compile everything on the command line

**Comment by marchbold** [comment]
Ah actually we don't have those files in the repository sorry, ignore that. At a bit of a loss as to what's happening on your machine. What version of windows are you using? I'll try and setup an identical vm to see if I can replicate.

**Comment by kakarlus** [comment]
im on a mac, OS X El Capitan 10.11.6

**Comment by marchbold** [comment]
Oh right, that makes even less sense. What version of AIR are you using?

**Comment by kakarlus** [comment]
here it is it's 25

```
<key>CFBundleVersion</key>
<string>25.0.0.134</string>
```

**Comment by kakarlus** [comment]
i just updated my AIR SDK to 26, same problem

**Comment by kakarlus** [comment]
does this have something to do with some values inside the build.xml? coz i have a different config xml file from `mxmlc -dump-config config.xml`

```
<!-- ACTIONSCRIPT LIBRARIES -->

	<target name="build_actionscript" >
		<echo message="Building actionscript library..."/>
		<compc output="${actionscript.dir}/bin/${actionscript.name}" debug="${DEBUG_MODE}" swf-version="17">
			<load-config filename="${air.sdk}/frameworks/air-config.xml" />
			<source-path path-element="${actionscript.dir}/src" />
			<include-sources dir="${actionscript.dir}/src" includes="*" />
		</compc>
		<echo message="done"/>
	</target>
	<target name="clean_actionscript" >
		<delete dir="${actionscript.dir}/bin" />
	</target>

	<target name="build_default" >
		<echo message="Building default library..."/>
		<compc output="${default.dir}/bin/${default.name}" debug="false" swf-version="17">
			<load-config filename="${air.sdk}/frameworks/air-config.xml" />
			<source-path path-element="${default.dir}/src" />
			<include-sources dir="${default.dir}/src" includes="*" />
		</compc>
		<echo message="done"/>
	</target>
	<target name="clean_default" >
		<delete dir="${default.dir}/bin" />
	</target>
```

**Comment by marchbold** [comment]
I wouldn't have thought so, it seems more like an issue with the android build, but what have you changed in your config?

**Comment by cevansOTBS** [comment]
Hello there,

First off thanks creating these products for Adobe Air. It doesn't seem like Adobe is doing much lately to create tools and extensions for Mobile Air, so I'm glad 3rd party devs such as yourself are picking up the slack. 

Anyway, I'm trying to generate a custom resource from the ANE-CustomResources project. I wish I found this topic earlier because I ran into many of the same issues as the others. I solved most of them, but now I'm hung up on this error when running ant on the "complle_windows:" stage.
"extension.build.xml: error 102: Invalid namespace http://ns.adobe.com/air/extension/4.0
build.xml:254: exec returned: 12

I'm using JDK 1.8.0_131, and the latest Android SDK installed via Android Studio.  And using 1.10.1 version of Ant. The FLEX/AIR SDK is 4.6.0 via Flash Builder. I'm not putting any other resources in the res folder. just trying to get the default project to run with my Firebase values.

The error 12 is a ADT exit error code, which says "Verify file paths and other arguments passed to ADT on the command line."

It would be great to get some ideas on what to do next to get pass this error. 

Also I found an error with one of your examples, which might be causing people problems. On the configurations wiki page here: https://github.com/distriqt/ANE-Firebase/wiki/Setup---Configuration-Files for your "values.xml"  example you have malformed XML. 

-- values.xml snippet --
    <! -- Present in all applications -->
    <string name="google_app_id" translatable="false">1:1035469437089:android:73a4fb8297b2cd4f</string>

    <! -- Present in applications with the appropriate services configured -->
    <string name="gcm_defaultSenderId" translatable="false">1035469437089</string>

-- values.xml end snippet

I'm sure like me others copied that example verbatim and then got an error during the build process. The problem is with the comments tag. The comments in the example have "<! --" instead of "<!--" which causes the xml to be malformed. So you may want to update the example on the Wiki page.

**Comment by marchbold** [comment]
Hi @cevansOTBS , 

Sounds like you may have an old version of AIR. Could you try updating the AIR SDK to version 25/26?

In future please post issues regarding the custom resources script in that repository. We are trying to keep the issues regarding that script out of the Firebase ANE.

**Comment by cevansOTBS** [comment]
Thank you, upgrading to AIR26 solved the problem! I was running AIR23. 

If I run into any further issues with the custom resource script, I'll be sure to post it in that repo.
Thanks again

**Comment by marchbold** [comment]
No problems at all, glad that solved your issue.

**Comment by embpdaniel** [comment]
@kakarlus I BELEIVE I had this same issue yesterday. What I noticed is that my values.xml file was in the wrong location. I had to place it under` res/values/values.xml`, and not in `res/values.xml`. Try that, maybe it will do the trick.

**Comment by marchbold** [comment]
@embpdaniel Ah yes that would produce the error!

**Comment by kakarlus** [comment]
@embpdaniel superb! thank you!

**Comment by ilyaround** [comment]
`@kakarlus I BELEIVE I had this same issue yesterday. What I noticed is that my values.xml file was in the wrong location. I had to place it underres/values/values.xml, and not in res/values.xml. Try that, maybe it will do the trick.`

I had the same issue
